name: AutoSubSync Test Manylinux

on:
  workflow_dispatch:

env:
  DIST_DIR: /tmp/builds

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build: win-x64
            file_name: win_amd64
          - os: macos-latest
            build: osx-arm64
            file_name: macos_arm64
          - os: macos-13
            build: macos-amd64
            file_name: macos_amd64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.8
          cache: "pip"

      - name: Install required modules globally
        run: |
          pip install requests

      - name: Run build script
        run: |
          python build.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.file_name }}
          path: |
            dist/*.zip
            dist/*.tar.gz

  build-linux-manylinux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build in manylinux container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
            quay.io/pypa/manylinux2014_x86_64 \
            bash -c "
              yum update -y && \
              yum install -y tk-devel tcl-devel gcc && \
              # Set up Python environment with proper linking
              cd /opt/python/cp312-cp312 && \
              ln -sf lib/libpython3.12.so.1.0 lib/libpython3.12.so && \
              # Create additional symlinks in standard locations
              ln -sf /opt/python/cp312-cp312/lib/libpython3.12.so.1.0 /usr/lib64/libpython3.12.so.1.0 && \
              ln -sf /opt/python/cp312-cp312/lib/libpython3.12.so.1.0 /usr/lib64/libpython3.12.so && \
              # Set environment variables
              export LD_LIBRARY_PATH=\"/opt/python/cp312-cp312/lib:/usr/lib64:\$LD_LIBRARY_PATH\" && \
              export PATH=\"/opt/python/cp312-cp312/bin:\$PATH\" && \
              export PYTHONHOME=\"/opt/python/cp312-cp312\" && \
              # Create custom PyInstaller configuration if needed
              mkdir -p /root/.pyinstaller && \
              echo -e \"import os\\nos.environ['LD_LIBRARY_PATH'] = '/opt/python/cp312-cp312/lib:/usr/lib64:' + os.environ.get('LD_LIBRARY_PATH', '')\" > /root/.pyinstaller/config.py && \
              # Install required packages
              python3.12 -m pip install --upgrade pip && \
              python3.12 -m pip install requests && \
              cd /workspace && \
              # Debug information
              echo \"Python library location:\" && \
              find /opt/python/cp312-cp312 -name 'libpython*.so*' && \
              echo \"Symlinks created:\" && \
              ls -la /usr/lib64/libpython* && \
              # Run build script
              python3.12 build.py && \
              find ./main/resources -type f -exec chmod +x {} \; 2>/dev/null || true
            "
            "

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-manylinux_amd64
          path: |
            dist/*.zip
            dist/*.tar.gz