name: AutoSubSync Test Manylinux

on:
  workflow_dispatch:

env:
  DIST_DIR: /tmp/builds

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build: win-x64
            file_name: win_amd64
          - os: macos-latest
            build: osx-arm64
            file_name: macos_arm64
          - os: macos-13
            build: macos-amd64
            file_name: macos_amd64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.8
          cache: "pip"

      - name: Install required modules globally
        run: |
          pip install requests

      - name: Run build script
        run: |
          python build.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.file_name }}
          path: |
            dist/*.zip
            dist/*.tar.gz

  build-linux-manylinux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build in manylinux container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
            quay.io/pypa/manylinux_2_28_x86_64 \
            bash -c "
              # Install system dependencies
              yum install -y tk-devel tcl-devel gcc which && \
              # Find Python 3.12 in the container
              PYTHON_DIR=\$(find /opt/python -name 'cp312*' | sort | head -n 1) && \
              echo \"Using Python directory: \${PYTHON_DIR}\" && \
              # Set environment variables
              export LD_LIBRARY_PATH=\"\${PYTHON_DIR}/lib:\$LD_LIBRARY_PATH\" && \
              export PATH=\"\${PYTHON_DIR}/bin:\$PATH\" && \
              export PYTHONHOME=\"\${PYTHON_DIR}\" && \
              # Create virtual environment
              \${PYTHON_DIR}/bin/python -m venv /workspace/venv && \
              source /workspace/venv/bin/activate && \
              # Install build dependencies
              pip install --upgrade pip && \
              pip install requests pyinstaller==6.14.0 && \
              # Debug information
              echo \"Python version:\" && \
              python --version && \
              echo \"PyInstaller version:\" && \
              pyinstaller --version && \
              echo \"Python library location:\" && \
              find \${PYTHON_DIR} -name 'libpython*.so*' && \
              # Set paths for PyInstaller
              export PYTHONPATH=\"\${PYTHON_DIR}/lib\" && \
              # Run build script
              cd /workspace && \
              python build.py && \
              # Make sure all files are executable
              find ./main/resources -type f -exec chmod +x {} \; 2>/dev/null || true
            "

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-manylinux_amd64
          path: |
            dist/*.zip
            dist/*.tar.gz