name: AutoSubSync Test

on:
  workflow_dispatch:

env:
  DIST_DIR: /tmp/builds

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build: win-x64
            file_name: win_amd64
          - os: macos-latest
            build: osx-arm64
            file_name: macos_arm64
          - os: macos-13
            build: macos-amd64
            file_name: macos_amd64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.8
          cache: "pip"

      - name: Install required modules globally
        run: |
          pip install requests

      - name: Run build script
        run: |
          python build.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.file_name }}
          path: |
            AutoSubSync-v*.zip
            AutoSubSync-v*.tar.gz

  build-linux-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build using build.py with Python 3.12
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
            --env DEBIAN_FRONTEND=noninteractive \
            --env TZ=Etc/UTC \
            --entrypoint bash \
            python:3.12.8-slim \
            -c "apt-get update && \
                apt-get install -y tzdata tk-dev && \
                echo 'GLIBC Version:' && \
                ldd --version | head -n 1 && \
                pip install --upgrade pip setuptools wheel requests pyinstaller && \
                python build.py"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-ubuntu2004_amd64
          path: |
            AutoSubSync-v*.zip
            AutoSubSync-v*.tar.gz