name: AutoSubSync Test Manylinux

on:
  workflow_dispatch:

env:
  DIST_DIR: /tmp/builds

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build: win-x64
            file_name: win_amd64
          - os: macos-latest
            build: osx-arm64
            file_name: macos_arm64
          - os: macos-13
            build: macos-amd64
            file_name: macos_amd64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.8
          cache: "pip"

      - name: Install required modules globally
        run: |
          pip install requests

      - name: Run build script
        run: |
          python build.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.file_name }}
          path: |
            AutoSubSync-v*.zip
            AutoSubSync-v*.tar.gz

  build-linux-manylinux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Build using build.py in pyinstaller-manylinux container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
            --entrypoint bash \
            ghcr.io/oleksis/pyinstaller-manylinux:latest \
            -c "python3.12 -m pip install --upgrade pip setuptools wheel && python3.12 build.py"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-manylinux_amd64
          path: |
            AutoSubSync-v*.zip
            AutoSubSync-v*.tar.gz